### ISSUE TITLE
Breaks with Ember 3.16+?

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-test-waiters#125]
Previously reported (with some exploration / discovery) here: https://github.com/bendemboski/ember-concurrency-test-waiter/issues/15

I know this lib recently had a breaking change, but since I'm not directly using ember-test-waiters, the breaking was surprising to me.

C.I. run: https://github.com/NullVoxPopuli/emberclear/pull/558/checks?check_run_id=476263612
Error:
```
not ok 1 Chrome 80.0 - [191 ms] - Acceptance | Settings | Relays > when logged in: the default relays are rendered
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read property 'TestWaiter' of undefined
                at Object.get [as TestWaiter] (https://0.0.0.0:7357/assets/vendor.js:101768:21)
                at reset (https://0.0.0.0:7357/assets/vendor.js:91619:45)
```

Project Search: 
![image](https://user-images.githubusercontent.com/199018/75610114-5e52a180-5adc-11ea-8046-b58f16184b04.png)

---------------

Debugging further,
running locally, (in firefox): 
![image](https://user-images.githubusercontent.com/199018/75610224-3adc2680-5add-11ea-96ef-80987ff3b8e8.png)
the error is that _types is undefined?

![image](https://user-images.githubusercontent.com/199018/75610245-6ced8880-5add-11ea-91fd-b8c1ce4496e6.png)

Debugging the stack trace:
![image](https://user-images.githubusercontent.com/199018/75610321-3feda580-5ade-11ea-9642-8aacdceb70b2.png)

looks like that is in `ember-app-scheduler/scheduler`?
never heard of this package. 

Near the top of vendor.js, (maybe in requirejs?),
![image](https://user-images.githubusercontent.com/199018/75610408-e6d24180-5ade-11ea-8fbc-a60a087e93ea.png)

Hypothesis / Question:
 - are there TS types leaking into the build output?

**Comment by scalvert** [comment]
Is this specifically an issue with Ember 3.16? It seems like the original PR reved the version of `ember-test-waiters` to `2.0.0`. 

There was an internal rename of the core `TestWaiter` class from that name to `TestWaiterImpl` to accommodate a rename to interfaces. It seems this could be related.

For the issue with `ember-app-scheduler` (which I also help maintain), I can make an update to that repo to resolve the issue.

**Comment by scalvert** [comment]
Fix for app scheduler: https://github.com/ember-app-scheduler/ember-app-scheduler/pull/597

**Comment by rwjblue** [comment]
Hmm, the test waiter class itself was never intended to be exposed externally...

**Comment by rwjblue** [comment]
I think this was fixed, closing for now...
