### ISSUE TITLE
Glimmer Standalone

### ISSUE THREAD

**Issue by josemarluedke** [emberjs/ember-test-waiters#243]
I'm building an addon/lib to use in Ember and Glimmer standalone (No Ember). The project is for fetching data, so having built-in support for waiting when network requests are done is essential. 

Looking at the code, this project doesn't seem too reliable in Ember itself. So what would it take to make it compatible with Glimmer?

**Comment by josemarluedke** [comment]
I have been thinking more about this and I believe this project is too much tight to Ember, which would require a lot of work around it. 

Closing for now.

**Comment by rwjblue** [comment]
Actually, I think your original assessment was correct. I actually think the only thing where Ember integration is needed is for the fallback / legacy behavior of registering a test helper (when on a version of `@ember/test-helpers` that doesn't use `@ember/test-waiters`).
