### ISSUE TITLE
@Waitfor does not work as promised

### ISSUE THREAD

**Issue by villander** [emberjs/ember-test-waiters#253]
I'm using `import { waitFor } from '@ember/test-waiters';` in the action inside component: 

```js
@action
@waitFor
 setListenersToAnimate(element: HTMLElement): void {
    this.elementToAnimate = element;

    document.addEventListener('scroll', this.canAnimateCheck);
    window.addEventListener('resize', this.canAnimateCheck);

    this.canAnimateCheck();
  }
 ```
 
 But I'm receiving this error on tests:
 
 
![image](https://user-images.githubusercontent.com/10222774/118158145-c8a9e600-b3f1-11eb-9e5a-156164aca99c.png)

**Comment by scalvert** [comment]
Thanks for the report. Any chance you could provide a minimal reproduction for us?

**Comment by scalvert** [comment]
Looking again at your usage, it doesn't look it fits one of the use cases for `waitFor`. As per [our docs](https://github.com/emberjs/ember-test-waiters#waitfor-function), you should either be using:

1. An async function
2. A generator
3. An ember-concurrency task

Am I missing something?

**Comment by stefanpenner** [comment]
I am going to close this issue, but If I am closing in error feel free to let me know and I'll gladly reopen :)
