### ISSUE TITLE
forceHighlanderAddon is not safe under embroider

### ISSUE THREAD

**Issue by ef4** [emberjs/ember-test-waiters#271]
Because embroider respects node_modules resolution rules, it's not OK to null out one copy of this package and assume that another copy will serve instead. Not every consumer of the nulled-out copy is guaranteed to be able to resolve the remaining copy.

This comes up particularly in monorepos, where the copy that is nulled-out may be at the monorepo root and the winning copy can be down inside one workspace.

If it's important that only one copy of test-waiter exists, then it should be a peerDep of each package that uses it, all the way up the dependency tree to the application, which should install it.

Alternatively, every copy needs to end up with working code. Instead of nulling out the losing copies, they should delegate to the winning copy to emit some code that will properly connect them with the winning copy.

**Comment by rwjblue** [comment]
That code was fixed in https://github.com/emberjs/ember-test-waiters/pull/231, and released in `@ember/test-waiters@2.4.0`.

**Comment by ef4** [comment]
Oh ok, great, I was looking at an earlier release.
