### ISSUE TITLE
Build error with embroider

### ISSUE THREAD

**Issue by enspandi** [emberjs/ember-test-waiters#349]
Trying to set up embroider - I ran into this build issue:

```
Build Error (PackagerRunner) in ../../node_modules/@ember/test-waiters/index.ts

Module parse failed: Unexpected token (1:7)
File was processed with these loaders:
 * ...node_modules/@embroider/babel-loader-8/index.js
You may need an additional loader to handle the result of these loaders.
> export type { WaiterName, Token, Primitive, Waiter, TestWaiter, TestWaiterDebugInfo, PendingWaiterState } from './types';
```

---

Is this maybe because of the `main` field pointing to the index.ts instead of index.js?

https://github.com/emberjs/ember-test-waiters/blob/master/package.json#L14

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by aaronucsd** [comment]
I'm getting the same error
``` 
ERROR in ../../node_modules/@ember/test-helpers/-internal/debug-info.js 19:0-60
Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/bfc6a7/node_modules/@ember/test-helpers/-internal'
 @ ./assets/test.js 46:9-82
```

**Comment by scalvert** [comment]
@enspandi ya I don't think it's supposed to point to a .ts file. I can look at fixing this.

@aaronucsd that error isn't the same as the one above. That looks like a problem with your local topology in your node_modules. I'd blow it away and install again.
